kind: pipeline
type: kubernetes
name: default

steps:
  - name: minioclient
    image: minio/mc
    commands:
      - sleep 15
      - mc config host add myminio http://localhost:9000 minioadmin minioadmin
      - mc rm -r --force myminio/gifbucket
      - mc mb myminio/gifbucket
      - mc policy download myminio/gifbucket

  - name: render
    image: golang
    commands:
      - mkdir /tmp/objcache
      - cp -r gifcreator/scene /tmp/
      - cd render
      - go get -v
      - go build -v
      - go test -v

  - name: gifcreator
    image: golang
    commands:
      - cd gifcreator
      - cp -r scene /tmp
      - go get -v
      - go build -v
      - go test -v


services:
- name: minioserver
  image: minio/minio

- name: database
  image: redis:5
