services:
  valkey:
    container_name: valkey
    image: docker.io/valkey/valkey:latest
    ports:
      - "6379:6379"
    networks:
      - gifnet

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioaccesskeyid"
      MINIO_ROOT_PASSWORD: "miniosecretaccesskey"
    networks:
      - gifnet

  render:
    container_name: render
    build:
      context: .
      dockerfile: Dockerfile
    command: /render
    ports:
      - "8085:8085"
    environment:
      RENDER_PORT: "8085"
      MINIO_NAME: "minio"
    networks:
      - gifnet

  gifcreator-server:
    container_name: gifcreator-server
    build:
      context: .
      dockerfile: Dockerfile
    command: /gifcreator
    ports:
      - "8082:8082"
    environment:
      MINIO_NAME: minio
      REDIS_NAME: valkey
      REDIS_PORT: "6379"
      RENDER_NAME: render
      RENDER_PORT: "8085"
    networks:
      - gifnet

  gifcreator-worker:
    container_name: gifcreator-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: /gifcreator -worker
    ports:
      - "8081:8081"
    environment:
      MINIO_NAME: minio
      REDIS_NAME: valkey
      REDIS_PORT: "6379"
      RENDER_NAME: render
      RENDER_PORT: "8085"
    networks:
      - gifnet

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    command: /frontend
    ports:
      - "8090:8090"
    environment:
      FRONTEND_PORT: "8090"
      GIFCREATOR_NAME: "gifcreator-server"
      GIFCREATOR_PORT: "8082"
    networks:
      - gifnet

networks:
  gifnet:
    driver: bridge
