//
// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gifcreator.proto

package proto

import (
	grpc_health_v1 "google.golang.org/grpc/health/grpc_health_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product int32

const (
	Product_UNKNOWN_PRODUCT Product = 0
	Product_GRPC            Product = 1
	Product_KUBERNETES      Product = 2
	Product_GO              Product = 3
)

// Enum value maps for Product.
var (
	Product_name = map[int32]string{
		0: "UNKNOWN_PRODUCT",
		1: "GRPC",
		2: "KUBERNETES",
		3: "GO",
	}
	Product_value = map[string]int32{
		"UNKNOWN_PRODUCT": 0,
		"GRPC":            1,
		"KUBERNETES":      2,
		"GO":              3,
	}
)

func (x Product) Enum() *Product {
	p := new(Product)
	*p = x
	return p
}

func (x Product) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Product) Descriptor() protoreflect.EnumDescriptor {
	return file_gifcreator_proto_enumTypes[0].Descriptor()
}

func (Product) Type() protoreflect.EnumType {
	return &file_gifcreator_proto_enumTypes[0]
}

func (x Product) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Product.Descriptor instead.
func (Product) EnumDescriptor() ([]byte, []int) {
	return file_gifcreator_proto_rawDescGZIP(), []int{0}
}

type GetJobResponse_Status int32

const (
	GetJobResponse_UNKNOWN_STATUS GetJobResponse_Status = 0
	GetJobResponse_PENDING        GetJobResponse_Status = 1
	GetJobResponse_DONE           GetJobResponse_Status = 2
	GetJobResponse_FAILED         GetJobResponse_Status = 3
)

// Enum value maps for GetJobResponse_Status.
var (
	GetJobResponse_Status_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "PENDING",
		2: "DONE",
		3: "FAILED",
	}
	GetJobResponse_Status_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"PENDING":        1,
		"DONE":           2,
		"FAILED":         3,
	}
)

func (x GetJobResponse_Status) Enum() *GetJobResponse_Status {
	p := new(GetJobResponse_Status)
	*p = x
	return p
}

func (x GetJobResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetJobResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_gifcreator_proto_enumTypes[1].Descriptor()
}

func (GetJobResponse_Status) Type() protoreflect.EnumType {
	return &file_gifcreator_proto_enumTypes[1]
}

func (x GetJobResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetJobResponse_Status.Descriptor instead.
func (GetJobResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_gifcreator_proto_rawDescGZIP(), []int{3, 0}
}

type StartJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO(light): what scene parameters do we want to give?
	Name          string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProductToPlug Product `protobuf:"varint,2,opt,name=product_to_plug,json=productToPlug,proto3,enum=gifinator.Product" json:"product_to_plug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_gifcreator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gifcreator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_gifcreator_proto_rawDescGZIP(), []int{0}
}

func (x *StartJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartJobRequest) GetProductToPlug() Product {
	if x != nil {
		return x.ProductToPlug
	}
	return Product_UNKNOWN_PRODUCT
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_gifcreator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gifcreator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_gifcreator_proto_rawDescGZIP(), []int{1}
}

func (x *StartJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_gifcreator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gifcreator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_gifcreator_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status GetJobResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=gifinator.GetJobResponse_Status" json:"status,omitempty"`
	// World-readable URL for created image.
	ImageUrl      string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_gifcreator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gifcreator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_gifcreator_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobResponse) GetStatus() GetJobResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetJobResponse_UNKNOWN_STATUS
}

func (x *GetJobResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_gifcreator_proto protoreflect.FileDescriptor

const file_gifcreator_proto_rawDesc = "" +
	"\n" +
	"\x10gifcreator.proto\x12\tgifinator\x1a\x1bgrpc/health/v1/health.proto\"a\n" +
	"\x0fStartJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\x0fproduct_to_plug\x18\x02 \x01(\x0e2\x12.gifinator.ProductR\rproductToPlug\")\n" +
	"\x10StartJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xa8\x01\n" +
	"\x0eGetJobResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .gifinator.GetJobResponse.StatusR\x06status\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\"?\n" +
	"\x06Status\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03*@\n" +
	"\aProduct\x12\x13\n" +
	"\x0fUNKNOWN_PRODUCT\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01\x12\x0e\n" +
	"\n" +
	"KUBERNETES\x10\x02\x12\x06\n" +
	"\x02GO\x10\x032\xe2\x01\n" +
	"\n" +
	"GifCreator\x12C\n" +
	"\bStartJob\x12\x1a.gifinator.StartJobRequest\x1a\x1b.gifinator.StartJobResponse\x12=\n" +
	"\x06GetJob\x12\x18.gifinator.GetJobRequest\x1a\x19.gifinator.GetJobResponse\x12P\n" +
	"\x05Check\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.health.v1.HealthCheckResponseB.Z,gitlab.com/insanitywholesale/gifinator/protob\x06proto3"

var (
	file_gifcreator_proto_rawDescOnce sync.Once
	file_gifcreator_proto_rawDescData []byte
)

func file_gifcreator_proto_rawDescGZIP() []byte {
	file_gifcreator_proto_rawDescOnce.Do(func() {
		file_gifcreator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gifcreator_proto_rawDesc), len(file_gifcreator_proto_rawDesc)))
	})
	return file_gifcreator_proto_rawDescData
}

var file_gifcreator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gifcreator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gifcreator_proto_goTypes = []any{
	(Product)(0),                               // 0: gifinator.Product
	(GetJobResponse_Status)(0),                 // 1: gifinator.GetJobResponse.Status
	(*StartJobRequest)(nil),                    // 2: gifinator.StartJobRequest
	(*StartJobResponse)(nil),                   // 3: gifinator.StartJobResponse
	(*GetJobRequest)(nil),                      // 4: gifinator.GetJobRequest
	(*GetJobResponse)(nil),                     // 5: gifinator.GetJobResponse
	(*grpc_health_v1.HealthCheckRequest)(nil),  // 6: grpc.health.v1.HealthCheckRequest
	(*grpc_health_v1.HealthCheckResponse)(nil), // 7: grpc.health.v1.HealthCheckResponse
}
var file_gifcreator_proto_depIdxs = []int32{
	0, // 0: gifinator.StartJobRequest.product_to_plug:type_name -> gifinator.Product
	1, // 1: gifinator.GetJobResponse.status:type_name -> gifinator.GetJobResponse.Status
	2, // 2: gifinator.GifCreator.StartJob:input_type -> gifinator.StartJobRequest
	4, // 3: gifinator.GifCreator.GetJob:input_type -> gifinator.GetJobRequest
	6, // 4: gifinator.GifCreator.Check:input_type -> grpc.health.v1.HealthCheckRequest
	3, // 5: gifinator.GifCreator.StartJob:output_type -> gifinator.StartJobResponse
	5, // 6: gifinator.GifCreator.GetJob:output_type -> gifinator.GetJobResponse
	7, // 7: gifinator.GifCreator.Check:output_type -> grpc.health.v1.HealthCheckResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gifcreator_proto_init() }
func file_gifcreator_proto_init() {
	if File_gifcreator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gifcreator_proto_rawDesc), len(file_gifcreator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gifcreator_proto_goTypes,
		DependencyIndexes: file_gifcreator_proto_depIdxs,
		EnumInfos:         file_gifcreator_proto_enumTypes,
		MessageInfos:      file_gifcreator_proto_msgTypes,
	}.Build()
	File_gifcreator_proto = out.File
	file_gifcreator_proto_goTypes = nil
	file_gifcreator_proto_depIdxs = nil
}
