// Code generated by protoc-gen-go. DO NOT EDIT.
// source: render.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RenderRequest struct {
	// GCS path to write output image into.
	GcsOutputBase string `protobuf:"bytes,1,opt,name=gcs_output_base,json=gcsOutputBase,proto3" json:"gcs_output_base,omitempty"`
	// scene object file (in .obj format) GCS path
	ObjPath string `protobuf:"bytes,2,opt,name=obj_path,json=objPath,proto3" json:"obj_path,omitempty"`
	// assets (like material files and images) to be associated with the object
	Assets []string `protobuf:"bytes,3,rep,name=assets,proto3" json:"assets,omitempty"`
	// scene rotation (in radians)
	Rotation float32 `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	// num iterations
	Iterations           int32    `protobuf:"varint,5,opt,name=iterations,proto3" json:"iterations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderRequest) Reset()         { *m = RenderRequest{} }
func (m *RenderRequest) String() string { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()    {}
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9004acb5e772af, []int{0}
}

func (m *RenderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderRequest.Unmarshal(m, b)
}
func (m *RenderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderRequest.Marshal(b, m, deterministic)
}
func (m *RenderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderRequest.Merge(m, src)
}
func (m *RenderRequest) XXX_Size() int {
	return xxx_messageInfo_RenderRequest.Size(m)
}
func (m *RenderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderRequest proto.InternalMessageInfo

func (m *RenderRequest) GetGcsOutputBase() string {
	if m != nil {
		return m.GcsOutputBase
	}
	return ""
}

func (m *RenderRequest) GetObjPath() string {
	if m != nil {
		return m.ObjPath
	}
	return ""
}

func (m *RenderRequest) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *RenderRequest) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

func (m *RenderRequest) GetIterations() int32 {
	if m != nil {
		return m.Iterations
	}
	return 0
}

type RenderResponse struct {
	// GCS path image was written to.
	GcsOutput            string   `protobuf:"bytes,1,opt,name=gcs_output,json=gcsOutput,proto3" json:"gcs_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderResponse) Reset()         { *m = RenderResponse{} }
func (m *RenderResponse) String() string { return proto.CompactTextString(m) }
func (*RenderResponse) ProtoMessage()    {}
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9004acb5e772af, []int{1}
}

func (m *RenderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderResponse.Unmarshal(m, b)
}
func (m *RenderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderResponse.Marshal(b, m, deterministic)
}
func (m *RenderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderResponse.Merge(m, src)
}
func (m *RenderResponse) XXX_Size() int {
	return xxx_messageInfo_RenderResponse.Size(m)
}
func (m *RenderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderResponse proto.InternalMessageInfo

func (m *RenderResponse) GetGcsOutput() string {
	if m != nil {
		return m.GcsOutput
	}
	return ""
}

func init() {
	proto.RegisterType((*RenderRequest)(nil), "renderdemo.RenderRequest")
	proto.RegisterType((*RenderResponse)(nil), "renderdemo.RenderResponse")
}

func init() { proto.RegisterFile("render.proto", fileDescriptor_ae9004acb5e772af) }

var fileDescriptor_ae9004acb5e772af = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xe9, 0xf6, 0x6d, 0xdf, 0x76, 0x74, 0x0a, 0xb9, 0x90, 0x6e, 0xa0, 0x94, 0x5d, 0x48,
	0x2f, 0xa4, 0x05, 0xfd, 0x07, 0x43, 0xbc, 0x54, 0xc9, 0xa5, 0x37, 0x23, 0xdd, 0x8e, 0x6d, 0x46,
	0x9b, 0x53, 0x73, 0x4e, 0x11, 0xff, 0x90, 0xbf, 0x53, 0x48, 0xe7, 0xa6, 0xe0, 0x55, 0xf2, 0xbc,
	0x49, 0xc8, 0xf3, 0x1e, 0x38, 0xf5, 0xe8, 0xb6, 0xe8, 0xb3, 0xd6, 0x93, 0x90, 0x82, 0x9e, 0xb6,
	0xd8, 0xd0, 0xf2, 0x33, 0x82, 0x99, 0x0e, 0xa8, 0xf1, 0xad, 0x43, 0x16, 0x75, 0x0d, 0xe7, 0xe5,
	0x86, 0xd7, 0xd4, 0x49, 0xdb, 0xc9, 0xba, 0x30, 0x8c, 0x71, 0x94, 0x44, 0xe9, 0x54, 0xcf, 0xca,
	0x0d, 0x3f, 0x85, 0x74, 0x65, 0x18, 0xd5, 0x1c, 0x26, 0x54, 0xec, 0xd6, 0xad, 0x91, 0x2a, 0x1e,
	0x84, 0x0b, 0xff, 0xa9, 0xd8, 0x3d, 0x1b, 0xa9, 0xd4, 0x05, 0x8c, 0x0d, 0x33, 0x0a, 0xc7, 0xc3,
	0x64, 0x98, 0x4e, 0xf5, 0x9e, 0xd4, 0x02, 0x26, 0x9e, 0xc4, 0x88, 0x25, 0x17, 0xff, 0x4b, 0xa2,
	0x74, 0xa0, 0x0f, 0xac, 0xae, 0x00, 0xac, 0xa0, 0x0f, 0xc0, 0xf1, 0x28, 0x89, 0xd2, 0x91, 0xfe,
	0x91, 0x2c, 0x73, 0x38, 0xfb, 0xf6, 0xe4, 0x96, 0x1c, 0xa3, 0xba, 0x04, 0x38, 0x8a, 0xee, 0x1d,
	0xa7, 0x07, 0xc7, 0xdb, 0x47, 0x18, 0xf7, 0x0f, 0xd4, 0x3d, 0x9c, 0xf4, 0xbb, 0x07, 0x6f, 0x1a,
	0x54, 0xf3, 0xec, 0xd8, 0x3f, 0xfb, 0xd5, 0x7d, 0xb1, 0xf8, 0xeb, 0xa8, 0xff, 0x6e, 0x95, 0xbd,
	0xdc, 0x94, 0x56, 0x6a, 0x53, 0x64, 0x1b, 0x6a, 0x72, 0xeb, 0xd8, 0x38, 0x2b, 0x1f, 0xef, 0x15,
	0xd5, 0xc8, 0xa6, 0xc6, 0xbc, 0xb4, 0xaf, 0xd6, 0x19, 0x21, 0x9f, 0x87, 0x29, 0x17, 0xe3, 0xb0,
	0xdc, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xde, 0x31, 0xb4, 0x7c, 0x01, 0x00, 0x00,
}
